### ISSUE TITLE
save_state_dict

### ISSUE THREAD

**Issue by dearleiii** [dearleiii/PIRM-2018#11]
Epoch 5, 85%     train_loss: 4.83 took: 18.79s
18 score::  torch.Size([40, 1]) outputs:  torch.Size([40, 1])
19 score::  torch.Size([40, 1]) outputs:  torch.Size([40, 1])
20 score::  torch.Size([1, 1]) outputs:  torch.Size([1, 1])
Epoch 5, 100%    train_loss: 3.22 took: 4.16s
Traceback (most recent call last):
  File "scatter_kernel3.py", line 156, in <module>
    approximator.save_state_dict('APXM_4conv.pt')
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'save_state_dict'

**Comment by dearleiii** [comment]
[github repo page for saving model](https://github.com/pytorch/pytorch/blob/761d6799beb3afa03657a71776412a2171ee7533/docs/source/notes/serialization.rst)


Recommended approach for saving a model

There are two main approaches for serializing and restoring a model.

The first (recommended) saves and loads only the model parameters:

`torch.save(the_model.state_dict(), PATH)
`Then later:

```
the_model = TheModelClass(*args, **kwargs)
the_model.load_state_dict(torch.load(PATH))
```
The second saves and loads the entire model:

torch.save(the_model, PATH)
Then later:

`the_model = torch.load(PATH)
`However in this case, the serialized data is bound to the specific classes and the exact directory structure used, so it can break in various ways when used in other projects, or after some serious refactors.
