### ISSUE TITLE
Add testing data to model directly 

### ISSUE THREAD

**Issue by dearleiii** [dearleiii/PIRM-2018#16]
===== HYPERPARAMETERS =====
batch_size= 50
epochs= 100
learning_rate= 0.001
==============================
0 score::  torch.Size([50, 1]) outputs:  torch.Size([50, 1])
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "model1.py", line 219, in <module>
    trainNet(approximator, batch_size = 50, n_epochs = 100, learning_rate = 0.001)
  File "model1.py", line 153, in trainNet
    optimizer.step()
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/torch/optim/adam.py", line 76, in step
    state['exp_avg_sq'] = torch.zeros_like(p.data)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by dearleiii** [comment]
Using Encoding.nn.DataParallel source code for GPU average usage
