### ISSUE TITLE
disk storage: model corrupted 

### ISSUE THREAD

**Issue by dearleiii** [dearleiii/PIRM-2018#20]
leichen@gpu-compute3$ python3 load_model_test.py
Traceback (most recent call last):
  File "load_model_test.py", line 25, in <module>
    model1 = torch.load('/home/home2/leichen/SuperResolutor/Approx_discrim/model3/model3_2_full.pt', map_location = lambda storage, loc: storage) #map_location={"cuda:0":cpu})
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/torch/serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.

**Comment by dearleiii** [comment]
leichen@gpu-compute2$ ls -lh model3_2.pt
-rw-r--r-- 1 leichen leichen 1.1G Jul 20 03:58 model3_2.pt
leichen@gpu-compute2$ ls -lh model3_2_full.pt
-rw-r--r-- 1 leichen leichen 164M Jul 20 03:58 model3_2_full.pt
leichen@gpu-compute2$ ls -lh n4conv3_full.pt
-rw-r--r-- 1 leichen leichen 1.1G Jul 18 19:04 n4conv3_full.pt
leichen@gpu-compute2$ ls -lh n4conv3.pt
-rw-r--r-- 1 leichen leichen 1.1G Jul 18 19:03 n4conv3.pt
