### ISSUE TITLE
 load_state_dict     state_dict = state_dict.copy() AttributeError: 'function' object has no attribute 'copy'

### ISSUE THREAD

**Issue by dearleiii** [dearleiii/PIRM-2018#21]
```
leichen@gpu-compute3$ python3 load_model_test.py
Traceback (most recent call last):
  File "load_model_test.py", line 25, in <module>
    model1 = model1.load_state_dict(torch.load('/home/home2/leichen/SuperResolutor/Approx_discrim/model3/model3_2.pt', map_location = lambda storage, loc: storage)) #map_location={"cuda:0":cpu})
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 695, in load_state_dict
    state_dict = state_dict.copy()
AttributeError: 'function' object has no attribute 'copy'
```

**Comment by dearleiii** [comment]
model.state_dict is a function, so very likely you want to call it as model.state_dict(). Best regards Thomas


[mode.state_dict()](https://discuss.pytorch.org/t/attributeerror-function-object-has-no-attribute-items-error-when-loading-state-dict/12596)
