### ISSUE TITLE
Scatter Plot 

### ISSUE THREAD

**Issue by dearleiii** [dearleiii/PIRM-2018#4]
Traceback (most recent call last):
  File "issue_scores_size.py", line 155, in <module>
    plt.scatter(scores, scores, 'o', c = "g")
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3470, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4320, in scatter
    alpha=alpha
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/matplotlib/collections.py", line 929, in __init__
    self.set_sizes(sizes)
  File "/home/home2/leichen/.local/lib/python3.5/site-packages/matplotlib/collections.py", line 902, in set_sizes
    scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor
TypeError: ufunc 'sqrt' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
leichen@gpu-compute7>

**Comment by dearleiii** [comment]
scores.np()

Traceback (most recent call last):
  File "issue_scores_size.py", line 155, in <module>
    scores_np = scores.np()
AttributeError: 'Tensor' object has no attribute 'np'

**Comment by dearleiii** [comment]
Check the scatter documentation. Third argument is for size of points and should be scalar or array_like. I assume 'r' is for color so do the following:

plt.scatter(x, y, c='r')
